version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins_master
    restart: always
    volumes:
      - /var/jenkins_home:/var/jenkins_home
    expose:
      - 8080
      - 50000
    ports:
      - '8080:8080'
      - '50000:50000'